---
node_exporter_version: "1.9.0"
node_exporter_arch: "amd64"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_port: 9100
node_exporter_extra_args: ""
