---
- name: Create node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    system: true
    state: present

- name: Create node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    state: present

- name: Check current node_exporter version
  command: "{{ node_exporter_install_dir }}/node_exporter --version"
  register: node_exporter_current
  changed_when: false
  failed_when: false

- name: Download node_exporter {{ node_exporter_version }}
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: '0644'
  when: node_exporter_current.rc != 0 or node_exporter_version not in (node_exporter_current.stderr | default(''))

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: /tmp
    remote_src: true
  when: node_exporter_current.rc != 0 or node_exporter_version not in (node_exporter_current.stderr | default(''))

- name: Install node_exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_install_dir }}/node_exporter"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  notify: restart node_exporter
  when: node_exporter_current.rc != 0 or node_exporter_version not in (node_exporter_current.stderr | default(''))

- name: Install systemd unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart node_exporter

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    daemon_reload: true
    enabled: true
    state: started

- name: Clean up tarball
  file:
    path: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    state: absent

- name: Clean up extracted directory
  file:
    path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}"
    state: absent
